export const mockDesigns = [
  {
    id: 1,
    name: 'Bridal Royal Elegance',
    category: 'Bridal',
    categoryId: 'bridal',
    duration: '3-4 hours',
    price: 2500,
    image: null,
    description: 'Intricate bridal mehndi covering full hands and feet with royal motifs.',
    favorite: false,
  },
  {
    id: 2,
    name: 'Arabic Flow',
    category: 'Party',
    categoryId: 'party',
    duration: '1-2 hours',
    price: 1200,
    image: null,
    description: 'Elegant Arabic style with bold floral patterns and leafy trails.',
    favorite: true,
  },
  {
    id: 3,
    name: 'Indo Fusion',
    category: 'Casual',
    categoryId: 'casual',
    duration: '45 mins',
    price: 600,
    image: null,
    description: 'Modern Indo fusion blend perfect for everyday elegance.',
    favorite: false,
  },
  {
    id: 4,
    name: 'Festive Glow',
    category: 'Festive',
    categoryId: 'festive',
    duration: '2-3 hours',
    price: 1800,
    image: null,
    description: 'Vibrant festive patterns with glitter accents for celebrations.',
    favorite: true,
  },
  {
    id: 5,
    name: 'Backhand Bridal',
    category: 'Bridal',
    categoryId: 'bridal',
    duration: '2-3 hours',
    price: 2000,
    image: null,
    description: 'Beautiful backhand bridal design with peacock and floral motifs.',
    favorite: false,
  },
  {
    id: 6,
    name: 'Minimalist Chic',
    category: 'Casual',
    categoryId: 'casual',
    duration: '30 mins',
    price: 400,
    image: null,
    description: 'Clean, minimal patterns for a modern and sophisticated look.',
    favorite: false,
  },
  {
    id: 7,
    name: 'Party Sparkle',
    category: 'Party',
    categoryId: 'party',
    duration: '1 hour',
    price: 900,
    image: null,
    description: 'Dazzling party design with glitter and bold Arabic strokes.',
    favorite: true,
  },
  {
    id: 8,
    name: 'Diwali Special',
    category: 'Festive',
    categoryId: 'festive',
    duration: '1.5 hours',
    price: 1500,
    image: null,
    description: 'Traditional Diwali motifs with diyas and mandala patterns.',
    favorite: false,
  },
];

export const mockBookings = [
  {
    id: 1,
    designId: 1,
    designName: 'Bridal Royal Elegance',
    designCategory: 'Bridal',
    date: '2025-09-15',
    startTime: '10:00',
    endTime: '13:00',
    status: 'CONFIRMED',
    createdAt: '2025-09-01T08:00:00Z',
  },
  {
    id: 2,
    designId: 2,
    designName: 'Arabic Flow',
    designCategory: 'Party',
    date: '2025-09-20',
    startTime: '14:00',
    endTime: '16:00',
    status: 'PENDING',
    createdAt: '2025-09-05T10:00:00Z',
  },
  {
    id: 3,
    designId: 4,
    designName: 'Festive Glow',
    designCategory: 'Festive',
    date: '2025-08-25',
    startTime: '11:00',
    endTime: '14:00',
    status: 'COMPLETED',
    createdAt: '2025-08-15T09:00:00Z',
  },
  {
    id: 4,
    designId: 3,
    designName: 'Indo Fusion',
    designCategory: 'Casual',
    date: '2025-09-10',
    startTime: '16:00',
    endTime: '17:00',
    status: 'CANCELLED',
    createdAt: '2025-09-02T07:00:00Z',
  },
  {
    id: 5,
    designId: 5,
    designName: 'Backhand Bridal',
    designCategory: 'Bridal',
    date: '2025-10-01',
    startTime: '09:00',
    endTime: '12:00',
    status: 'PENDING',
    createdAt: '2025-09-10T06:00:00Z',
  },
];

export const mockAdminBookings = [
  {
    id: 101,
    clientName: 'Priya Sharma',
    clientEmail: 'priya@example.com',
    designName: 'Bridal Royal Elegance',
    designCategory: 'Bridal',
    date: '2025-09-15',
    startTime: '10:00',
    endTime: '13:00',
    status: 'CONFIRMED',
  },
  {
    id: 102,
    clientName: 'Anjali Mehta',
    clientEmail: 'anjali@example.com',
    designName: 'Arabic Flow',
    designCategory: 'Party',
    date: '2025-09-20',
    startTime: '14:00',
    endTime: '16:00',
    status: 'PENDING',
  },
  {
    id: 103,
    clientName: 'Sneha Patel',
    clientEmail: 'sneha@example.com',
    designName: 'Festive Glow',
    designCategory: 'Festive',
    date: '2025-08-25',
    startTime: '11:00',
    endTime: '14:00',
    status: 'COMPLETED',
  },
  {
    id: 104,
    clientName: 'Riya Joshi',
    clientEmail: 'riya@example.com',
    designName: 'Indo Fusion',
    designCategory: 'Casual',
    date: '2025-09-10',
    startTime: '16:00',
    endTime: '17:00',
    status: 'CANCELLED',
  },
];

export const categories = [
  { id: 'all', name: 'All', icon: '✨' },
  { id: 'bridal', name: 'Bridal', icon: '💍' },
  { id: 'party', name: 'Party', icon: '🎉' },
  { id: 'casual', name: 'Casual', icon: '☕' },
  { id: 'festive', name: 'Festive', icon: '🪔' },
];
